enum files {
  fEmpty,
  fTimeIs,
  fMinutes,
  fPast,
  fO,
  fOne,
  fTwo,
  fThree,
  fFour,
  fFive,
  fSix,
  fSeven,
  fEight,
  fNine,
  fTen,
  fEleven,
  fTwelve,
  fThirteen,
  fFourteen,
  fFifteen,
  fSixteen,
  fSeventeen,
  fEighteen,
  fNineteen,
  fTwenty,
  fThirty,
  fFourty,
  fFifty
};

const byte hours[] = {
  fTwelve,
  fOne,
  fTwo,
  fThree,
  fFour,
  fFive,
  fSix,
  fSeven,
  fEight,
  fNine,
  fTen,
  fEleven
};

const byte minutes[][3] = {
  {0, 0, 0},
  {fOne, 0, 0},
  {fTwo, 0, 0},
  {fThree, 0, 0},
  {fFour, 0, 0},
  {fFive, 0, 0},
  {fSix, 0, 0},
  {fSeven, 0, 0},
  {fEight, 0, 0},
  {fNine, 0, 0},
  {fTen, 0, 0},
  {fEleven, 0, 0},
  {fTwelve, 0, 0},
  {fThirteen, 0, 0},
  {fFourteen, 0, 0},
  {fFifteen, 0, 0},
  {fSixteen, 0, 0},
  {fSeventeen, 0, 0},
  {fEighteen, 0, 0},
  {fNineteen, 0, 0},
  {fTwenty, 0, 0},
  {fTwenty, fOne, 0},
  {fTwenty, fTwo, 0},
  {fTwenty, fThree, 0},
  {fTwenty, fFour, 0},
  {fTwenty, fFive, 0},
  {fTwenty, fSix, 0},
  {fTwenty, fSeven, 0},
  {fTwenty, fEight, 0},
  {fTwenty, fNine, 0},
  {fThirty, 0, 0},
  {fThirty, fOne, 0},
  {fThirty, fTwo, 0},
  {fThirty, fThree, 0},
  {fThirty, fFour, 0},
  {fThirty, fFive, 0},
  {fThirty, fSix, 0},
  {fThirty, fSeven, 0},
  {fThirty, fEight, 0},
  {fThirty, fNine, 0},
  {fFourty, 0, 0},
  {fFourty, fOne, 0},
  {fFourty, fTwo, 0},
  {fFourty, fThree, 0},
  {fFourty, fFour, 0},
  {fFourty, fFive, 0},
  {fFourty, fSix, 0},
  {fFourty, fSeven, 0},
  {fFourty, fEight, 0},
  {fFourty, fNine, 0},
  {fFifty, 0, 0},
  {fFifty, fOne, 0},
  {fFifty, fTwo, 0},
  {fFifty, fThree, 0},
  {fFifty, fFour, 0},
  {fFifty, fFive, 0},
  {fFifty, fSix, 0},
  {fFifty, fSeven, 0},
  {fFifty, fEight, 0},
  {fFifty, fNine, 0},
};
