#!/bin/sh

echo "Programming Arduino UNO to be Keyboard"
echo "If it's not working - make sure you've shorted the pins!"

sudo dfu-programmer atmega16u2 erase
sudo dfu-programmer atmega16u2 flash --debug 1 Arduino-keyboard-0.3.hex
sudo dfu-programmer atmega16u2 reset

echo "Aight - power cycle the Arduino!"